#! /usr/bin/env ruby

require 'json'

class Room
  def initialize(title, url)
    @title = title
    @url = url
  end

  def to_json(_)
    data.to_json
  end

  private

  def data
    {
      arg: @url,
      autocomplete: @title,
      subtitle: @url,
      text: { copy: @url },
      title: @title,
      uid: @title
    }
  end
end

items = [
  Room.new('Annex', 'http://zoom.us/my/artsyannex'),
  Room.new('Boardroom', 'http://zoom.us/my/artsyboardroom'),
  Room.new('Brainstorm', 'http://zoom.us/my/artsybrainstorm'),
  Room.new('Classroom', 'http://zoom.us/my/artsyclassroom'),
  Room.new('Den', 'http://zoom.us/my/artsyden'),
  Room.new('Lab', 'http://zoom.us/my/artsylab'),
  Room.new('Workshop', 'http://zoom.us/my/artsyworkshop')
]

feedback = { items: items }

print feedback.to_json
