#! /usr/bin/env ruby

require 'json'

class Room
  def initialize(title, room_id)
    @title = title
    @url = "http://zoom.us/my/#{room_id}"
  end

  def to_json(_)
    data.to_json
  end

  private

  def data
    {
      arg: @url,
      autocomplete: @title,
      subtitle: @url,
      text: { copy: @url },
      title: @title,
      uid: @title
    }
  end
end

items = [
  Room.new('Annex', 'artsyannex'),
  Room.new('Boardroom', 'artsyboardroom'),
  Room.new('Brainstorm', 'artsybrainstorm'),
  Room.new('Classroom', 'artsyclassroom'),
  Room.new('Den', 'artsyden'),
  Room.new('Lab', 'artsylab'),
  Room.new('Workshop', 'artsyworkshop')
]

feedback = { items: items }

print feedback.to_json
