#! /usr/bin/env ruby

require 'json'
require './scripts/item.rb'

base_url = 'https://dashboard.heroku.com/apps/REPLACE'
filename = 'data/dashboards.yml'

items = Item.build_from(filename, base_url)

feedback = { items: items }
print feedback.to_json
